
export let mesDonnees = {
  0 : ["Peux-tu me donner la race de ce chien ?","Berger allemand","Berger Malinois","Berger Australien","Désolé! Mauvaise réponse. La bonne réponse est Berger allemand"],
  1 : ["Peux-tu me donner la race de ce chien ?","Mastiff","Le Boerboel (ou Boerbull)","Bullmastiff","Désolé! Mauvaise réponse. La bonne réponse est Mastiff"],
  2 : ["Peux-tu me donner la race de ce chien ?","Bullmastiff","Le Boerboel (ou Boerbull)","Chien de Saint-Hubert","Désolé! Mauvaise réponse. La bonne réponse est Bullmastiff"],
  // 3 : ["Peux-tu me donner la race de ce chien ?","Chien de Saint-Hubert","Braque hongrois à poil court","American Staffordshire Terrier","Désolé! Mauvaise réponse. La bonne réponse est hien de Saint-Hubert"],
  // 4 : ["Peux-tu me donner la race de ce chien ?","Rottweiler","Amstaff","Staffordshire Bull Terrier","Désolé! Mauvaise réponse. La bonne réponse est Rottweiler"],
  // 5 : ["Peux-tu me donner la race de ce chien ?","Berger des Pyrénées","Grand bouvier suisse","Le Berger Australien","Désolé! Mauvaise réponse. La bonne réponse est Berger des Pyrénées"],
  // 6 : ["Peux-tu me donner la race de ce chien ?","Terre-neuve","Berger des Pyrénées","Le Léonberg","Désolé! Mauvaise réponse. La bonne réponse est Terre-neuve"],
  // 7 : ["Peux-tu me donner la race de ce chien ?","Dogue allemand","Le Mâtin Napolitain","Le Lévrier Irlandais","Désolé! Mauvaise réponse. La bonne réponse est Dogue allemand"],
  // 8 : ["Peux-tu me donner la race de ce chien ?","Golden retriever","Terre-neuve","Labrador Retriever","Désolé! Mauvaise réponse. La bonne réponse est Golden retriever"],
  // 9 : ["Peux-tu me donner la race de ce chien ?","Bouvier bernois","Grand bouvier suisse","Bouvier Des Ardennes","Désolé! Mauvaise réponse. La bonne réponse est Bouvier bernois"],
  // 10 : ["Peux-tu me donner la race de ce chien ?","Schnauzer géant","Le Terrier noir russe","Fox-terrier","Désolé! Mauvaise réponse. La bonne réponse est Schnauzer géant"],
  // 11 : ["Peux-tu me donner la race de ce chien ?","Cane Corso","Dogue allemand","Beauceron","Désolé! Mauvaise réponse. La bonne réponse est Cane Corso"],
  // 12 : ["Peux-tu me donner la race de ce chien ?","Terrier de Boston","Bouledogue Français","Carlin","Désolé! Mauvaise réponse. La bonne réponse est Terrier de Boston"],
  // 13 : ["Peux-tu me donner la race de ce chien ?","Cairn terrier","Yorkshire terrier","Spitz nain","Désolé! Mauvaise réponse. La bonne réponse est Cairn terrier"],
  // 14 : ["Peux-tu me donner la race de ce chien ?","Beagle","American Foxhound","Chien courant de Hamilton","Désolé! Mauvaise réponse. La bonne réponse est Beagle"],
  // 15 : ["Peux-tu me donner la race de ce chien ?","Cocker spaniel anglais","Berger Portugais","Setter Irlandais","Désolé! Mauvaise réponse. La bonne réponse est Cocker spaniel anglais"],
  // 16 : ["Peux-tu me donner la race de ce chien ?","Caniche nain","Le Bichon frisé","Le Pumi","Désolé! Mauvaise réponse. La bonne réponse est Caniche nain"],
  // 17 : ["Peux-tu me donner la race de ce chien ?","Teckel","Jack russel","Fox-terrier","Désolé! Mauvaise réponse. La bonne réponse est Teckel"],
  // 18 : ["Peux-tu me donner la race de ce chien ?","Bouledogue français","Boston Terrier","Carlin","Désolé! Mauvaise réponse. La bonne réponse est Bouledogue français"],
  // 19 : ["Peux-tu me donner la race de ce chien ?","Yorkshire terrier","cairn terrier","Chihuahua","Désolé! Mauvaise réponse. La bonne réponse est Yorkshire terrier"],
  // 20 : ["Peux-tu me donner la race de ce chien ?","Chihuahua","Yorkshire terrier","Le Spitz nain","Désolé! Mauvaise réponse. La bonne réponse est Chihuahua"],
  // 21 : ["Peux-tu me donner la race de ce chien ?","Carlin","Bouledogue Français","Pékinois","Désolé! Mauvaise réponse. La bonne réponse est Carlin"],
  // 22 : ["Peux-tu me donner la race de ce chien ?","Spitz nain","Cairn terrier","Chihuahua","Désolé! Mauvaise réponse. La bonne réponse est Spitz nain"],
  // 23 : ["Peux-tu me donner la race de ce chien ?","Jack Russel terrier","Le Fox-Terrier","Le Terrier Écossais","Désolé! Mauvaise réponse. La bonne réponse est Jack Russel terrier"],
  // 24 : ["Peux-tu me donner la race de ce chien ?","Basset","Chien courant espagnol","Boxer","Désolé! Mauvaise réponse. La bonne réponse est Basset"],
  // 25 : ["Peux-tu me donner la race de ce chien ?","Border collie","Bouvier bernois","Le Berger des Shetland","Désolé! Mauvaise réponse. La bonne réponse est Border collie"],
  // 26 : ["Peux-tu me donner la race de ce chien ?","Boxer","Dogo Canario","Dogue de Majorque","Désolé! Mauvaise réponse. La bonne réponse est Boxer"],
  // 27 : ["Peux-tu me donner la race de ce chien ?","Dalmatien","Le Dogue Allemand","Grand Épagneul de Münster","Désolé! Mauvaise réponse. La bonne réponse est Dalmatien"],
  // 28 : ["Peux-tu me donner la race de ce chien ?","Labrador retriever","Golden retriever","Setter anglais","Désolé! Mauvaise réponse. La bonne réponse est Labrador retriever"],
  // 29 : ["Peux-tu me donner la race de ce chien ?","Pit Bull terrier","Mastiff","Tosa","Désolé! Mauvaise réponse. La bonne réponse est Pit Bull terrier"],
  // 30 : ["Peux-tu me donner la race de ce chien ?","Bulldog","Pit Bull terrier","Boxer","Désolé! Mauvaise réponse. La bonne réponse est Bulldog"],
  // 31 : ["Peux-tu me donner la race de ce chien ?","Braque de Weimar","Chien d’Artois","Chien d'arrêt portugais","Désolé! Mauvaise réponse. La bonne réponse est Braque de Weimar"],
  // 32 : ["Peux-tu me donner la race de ce chien ?","Husky de Sibérie","Akita","Le Léonberg","Désolé! Mauvaise réponse. La bonne réponse est Husky de Sibérie"],
  // 33 : ["Peux-tu me donner la race de ce chien ?","Samoyède","Border collie","Le Berger des Shetland","Désolé! Mauvaise réponse. La bonne réponse est Samoyède"],
  // 34 : ["Peux-tu me donner la race de ce chien ?","Braque hongrois","Dogue allemand","Chien d’Artois","Désolé! Mauvaise réponse. La bonne réponse est Braque hongrois"],
  // 35 : ["Peux-tu me donner la race de ce chien ?","Chow-chow","Akita","Shiba inu","Désolé! Mauvaise réponse. La bonne réponse est Chow-chow"]
}

